### ISSUE TITLE
FEATURE: Add Last.fm Scrobbling

### ISSUE THREAD

**Issue by copey02** [Musish/Musish#187]
Add ability to directly scrobble to last.fm

**Comment by kiliankoe** [comment]
Oh my, if this is a possibility and were to be added I'd use nothing else 😍

**Comment by bonavox007** [comment]
Last.fm integration would be absolutely magic!!! Spotify have supported it for many years already. This web player is already good enough for me, but I've been scrobbling to Last.fm for many years now and is the only reason I still have to install iTunes. Well, not true... I still have to use iTunes for Smart Playlists and other special occasions, but on for every day use.

**Comment by kiliankoe** [comment]
LastFM support for iTunes is underwhelming at best. It doesn't pick up content not added to the library. Having everything scrobbled here would be fantastic!

**Comment by TheRealContz** [comment]
+1 It would be great!

**Comment by DiegoMarcondesD** [comment]
Please please!

**Comment by brandrick** [comment]
+1 on this! 🙏

**Comment by eriksf** [comment]
BTW, if you're a Chrome or Firefox user the Web Scrobbler plugin (https://chrome.google.com/webstore/detail/web-scrobbler/hhinaapppaileiechjoiifaancjggfjm?hl=en) will scrobble from Musish.

**Comment by SpartakusMd** [comment]
Is the plugin an accepted solution or do you want the site to do the scrobbling automatically after you give access to your Last.fm account ?

For Chrome and Firefox users it should be ok, but there are users on other browsers so I think it's better to have an in-house integration.

**Comment by TheRealContz** [comment]
I would like it integrated

**Comment by raphaelvigee** [comment]
You've all been waiting for it, here it is, Last.fm scrobbling! Connect your account from the cog menu

**Comment by TheRealContz** [comment]
I love you

**Comment by brandrick** [comment]
**Thank you so much! I'll be using Musish so much more now.** 

One thing that would be nice here is a _delay to the scrobble_. 

When I'm listening to a playlist I may skip something, so a 20 second delay _(or something like that)_ before sending the scrobble would be ace, as often a playlist may have something in it which I'm not a fan of and I'd rather not have it on my profile. 

Thanks again.
