### ISSUE TITLE
BUG: Album Information Incorrectly Pluralized

### ISSUE THREAD

**Issue by Paoda** [Musish/Musish#191]
**Describe the bug**
Incorrect grammar when displaying how many songs there are in an album when the song count is 1, and when displaying how long an album is when the total length is not 1 minute. 

**To Reproduce**
1. Search for "Let it Snow (YUC'e Remix) - Single"
2. Click on the album result.
3. See Error

**Expected behavior**
The text at the bottom left of the Album Panel should read "1 song, 4 minutes".

**Screenshots**
![chrome_2019-01-18_22-19-05](https://user-images.githubusercontent.com/22038970/51422149-4be30600-1b6f-11e9-9ee3-22f7722dc69c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 71

**Comment by SeanArmstrong** [comment]
Should be a simple fix for someone

https://github.com/Musish/Musish/blob/master/src/app/components/Common/AlbumPanel/AlbumPanel.jsx#L142

**Comment by BrychanOdlum** [comment]
Fixed by #250
