### ISSUE TITLE
BUG: sound mute button unexpectedly puts audio at 100%

### ISSUE THREAD

**Issue by codymikol** [Musish/Musish#194]
**Describe the bug**

Clicking the volume icon should always mute / unmute. 

**To Reproduce**

**Expected behavior**

If volume is at 50% clicking mute should mute the volume, unmute should return volume to 50%

**Screenshots**

![screen recording 2019-01-18 at 11 42 45 pm](https://user-images.githubusercontent.com/13606342/51422368-7c30a180-1b7b-11e9-8662-d607a5905c3b.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OS
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 71

**Additional context**

n/a

**Comment by jamesjarvis** [comment]
although +1 for gif
