### ISSUE TITLE
FEATURE: Add a favicon

### ISSUE THREAD

**Issue by wh4this** [Musish/Musish#204]
When I pin the musi.sh tab, there is no favicon with your logo.

**Comment by ondrejfuhrer** [comment]
Also would be great if there is also a logo when added to Safari Favourites 😉 Not 100% sure how that can be achieved, but my guess is through
```html
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
```

**Comment by raphaelvigee** [comment]
https://github.com/jantimon/favicons-webpack-plugin

**Comment by dragonwocky** [comment]
AFAICT all this needs to get it working is doing this in https://github.com/Musish/Musish/blob/master/webpack.config.js:
```js
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');
config.plugins.push(new FaviconsWebpackPlugin('path/to/image.png'));
```

I would try and make a PR, but don't have an Apple Dev token so I can't test run things (can I?).

(...also I'm struggling to find an image file for the logo)

**Comment by spinofdoom** [comment]
This is literally my only request from this amazing webapp.

**Comment by spinofdoom** [comment]
It would appear that the icon is indeed there, at https://github.com/Musish/Musish/blob/master/src/app/assets/fonts/musicon.svg, if I'm not mistaken. _However_, the code for that file doesn't seem to actually render an icon. 
If you type in the raw code to an SVG preview site like https://codepen.io/LeftyDesigner/pen/gLabt 
nothing appears.

**Comment by dragonwocky** [comment]
@spinofdoom that's the exact issue I ran into. It being a font rather than an image caused issues for me, but I assume the developers have or know how to get a version that would work for this.

**Comment by LiamBM** [comment]
This website really needs a favicon.

**Comment by SpectralKH** [comment]
Use https://realfavicongenerator.net/
