### ISSUE TITLE
FEATURE: Adding of songs to playlists

### ISSUE THREAD

**Issue by crash-slayer** [Musish/Musish#212]
**Is your feature request related to a problem? Please describe.**
If I like a song I'll usually want to add it to one of my playlists, currently the only option I get when I "right-click" on any song is to add it on my library.

**Describe the solution you'd like**
I want to be able to right-click on any song and have the option of adding it to anyone of my playlists.

**Comment by smitty-rh** [comment]
Didn't realize you can drag songs into the playlists so that does help, could be helpful even if there was an option when you choose the three dots to add to playlist.
