### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by irvingtelder** [Musish/Musish#229]
Searching Apple Music via Musish: Currently, searching for a song title gets a limited amount of results. This is also true via iTunes but with iTunes there's a "See All" link where you get another, more numerous but yet still limited result. If the AM API allows for deep searching it would be great to see in Musish.

**Comment by raphaelvigee** [comment]
To display the entire search, press "Enter" or the Search button. Otherwise you see a list of suggestions. Please reopen if it is still an issue.

**Comment by irvingtelder** [comment]
The "entire search" you describe is what I'm talking about. In iTunes, I can click a "See All" link above/right of the song results. This search is also obviously incomplete, however. Searching songs for "Yesterday" should give a LOT more results than 37...but Apple Music and iTunes sucks in this regard (as compared to Spotify). I was just wondering if Musish could improve on AM searching.
