### ISSUE TITLE
BUG: Unnecessary scrollbars

### ISSUE THREAD

**Issue by iSpid3r** [Musish/Musish#235]
- OS Windows 10
 - Browser Firefox 
 - Version 64.0.2

![22-01-2019 09-52-00](https://user-images.githubusercontent.com/20419104/51517316-634e1780-1e2b-11e9-9bbc-c1358f0be31e.jpg)

**Comment by dedeswim** [comment]
Another unnecessary scrollbar is here:
![image](https://user-images.githubusercontent.com/4366950/51597021-8c89a900-1efa-11e9-9af3-522f12dcfd80.png)
* Windows 10
* Chrome 71

**Comment by nugend** [comment]
`.ba2f {overflow: scroll}` needs to be changed to `auto`
