### ISSUE TITLE
Electron wrapper

### ISSUE THREAD

**Issue by andersfischernielsen** [Musish/Musish#238]
Musish is awesome, but has to be opened in a browser. Having Musish running as native-ish app on your machine could be preferable for some user (e.g. people running the Windows version of iTunes in Wine on Linux could use this wrapped native-ish instead for a better experience). 

Using [nativefier](https://github.com/jiahaog/nativefier) it is possible to wrap any webpage in an application shell. I tried attaching a wrapper for Musish for macOS to this issue as an example, but GitHub does not allow files bigger than 10MB (the `.app` is 50MB).
Having a wrapped version of Musish on the page of this project as a release might benefit some users. 😄 
Alternatively, a separate repo with wrappers for the three major platforms could be created where people can download them.

No code needs to be changed in `/src` since the wrapper just pulls the webpage into the shell.  
I wrapped Musish with `nativefier --name "Musish" "http://musi.sh"` and everything works as expected when opening the `.app`.

Feel free to reject this issue if it's out of scope for the project.

**Comment by andersfischernielsen** [comment]
<img width="1392" alt="screenshot 2019-01-22 at 11 58 49" src="https://user-images.githubusercontent.com/5990738/51531195-20953b00-1e3d-11e9-81df-ff9e26354ee5.png">

UPDATE: It seems the login redirect (open in Safari) does not work. I'm unsure if it **has** to open in the Electron wrapper in order to work. Weird.. 

Here's a screenshot of the "Browse" window working nonetheless.

**Comment by andersfischernielsen** [comment]
I just realised #234 is the exact same feature request.

**Comment by andersfischernielsen** [comment]
... and #190.

**Comment by plexb0t** [comment]
Until there's an Electron App or something similar, I built some kind of this nativefier script but with a permanent Apple Music.app file... It's based on Fluid and works quite well... you can grab it here: https://niko.yt/AppleMusic.dmg
I think it's fine for now 🤷🏼‍♂️ hope it can help you :)

**Comment by oxbown** [comment]
> Until there's a real Electron App or something similar, I built some kind of this nativefier script but with a permanent Apple Music.app file and a working login page! It's based on Fluid and works quite well... you can grab it here: https://niko.yt/AppleMusic.dmg
> I think it's fine for now 🤷🏼‍♂️ hope it can help you :)

Link down!

**Comment by plexb0t** [comment]
> > Until there's a real Electron App or something similar, I built some kind of this nativefier script but with a permanent Apple Music.app file and a working login page! It's based on Fluid and works quite well... you can grab it here: https://niko.yt/AppleMusic.dmg
> > I think it's fine for now 🤷🏼‍♂️ hope it can help you :)
> 
> Link down!

True, sorry! should work at https://niko.yt/AppleMusic now :)

**Comment by oxbown** [comment]
> > > Until there's a real Electron App or something similar, I built some kind of this nativefier script but with a permanent Apple Music.app file and a working login page! It's based on Fluid and works quite well... you can grab it here: https://niko.yt/AppleMusic.dmg
> > > I think it's fine for now 🤷🏼‍♂️ hope it can help you :)
> > 
> > 
> > Link down!
> 
> True, sorry! should work at https://niko.yt/AppleMusic now :)

Login does not work!!! Same result as Nativefier

**Comment by plexb0t** [comment]
Hmmm... for me it works and I explicitly enabled it to work... that's really unexpected 🤔

**Comment by oxbown** [comment]
It pops up a blank screen and a tab in safari, but just blank screens.

**Comment by plexb0t** [comment]
hmm okey... i had this problem too before I set it up so it worked properly... I'll quickly change the dmg so you are able to change it by yourself! :)

**Comment by plexb0t** [comment]
You can try it again now, then go to Preferences -> Whitelist and add `*.apple.com*` to the whitelist down below :)

**Comment by oxbown** [comment]
"Feature Not Available in Free Version"

**Comment by plexb0t** [comment]
What?! It is, where did you go to? 🤔

**Comment by BrychanOdlum** [comment]
I might set up a separate repo for this, perhaps with more specific support for an Electron app.

**Comment by schenkty** [comment]
I think Electron is by far the best option but I think it involves a bit more work than nativefier.

**Comment by dedeswim** [comment]
Another plus for an Electron version is the possibility to integrate with native functionalities such as key binding controls, or music player in the lock screen, as it is for Tidal's Windows client (that I am pretty sure is Electron-based)

**Comment by BrychanOdlum** [comment]
@dedeswim this is my aim here, this is a good opportunity for a much nicer experience!

I also want to add on some other functionality here such as local on-disk caching of artwork and even of library content (excluding actual audio files) which passively updates in the background. We should maybe give this a bit more thought before moving ahead.

**Comment by BrychanOdlum** [comment]
Has anyone been able to get the login window working?

I'm getting this:
```
URL: https://buy.itunes.apple.com/commerce/account/authenticateMusicKitRequest
Status: 405 Method Not Allowed
Source: Network
```

**Comment by BrychanOdlum** [comment]
Semi-answering my own question here:

The above request's method is GET. Natively in Chrome this is a POST with the JWT_TOKEN, isWebPlayer, and a LogoUrl (which is interestingly hard-coded as 'test' in musickit.js.

**Comment by BrychanOdlum** [comment]
<img width="1456" alt="screenshot 2019-01-24 at 01 23 48" src="https://user-images.githubusercontent.com/9306474/51668187-7c171400-1f76-11e9-9eb0-70e1beb13628.png">

(Also, a cute little progress picture)

**Comment by schenkty** [comment]
@BrychanOdlum I had the same issue and I haven’t figured out the solution either.

**Comment by BrychanOdlum** [comment]
@schenkty So we get a little bit further if we set `nativeWindowOpen` to true in the window's`webPreferences` options. Haven't had time to get beyond there yet.

**Comment by leolelego** [comment]
Should be awesome to be able to use natives audio keys (next, previous) on these web app 😊

**Comment by alx242** [comment]
Is this an alternative? https://nwjs.io/

Hoping that someone has time to try it instead of electron ;)

**Comment by AkazaDorian** [comment]
Would be glad to see a PWA app on Windows Store as well, not sure if M$ would allow it though. Shouldn't be any more work than nativefier.🤣

**Comment by LP0101** [comment]
I've put in a few hours into this as well. Furthest I get is using `nativeWindowOpen: true` and `affinity: 'main window` in `webPreferences`, but after logging in to the Apple Login popup, it just hangs without closing that window and redirecting the main application.

**Comment by LP0101** [comment]
Update: Using nw.js, I'm able to log in just fine, but I can't get audio to play, even when using the proper ffmpeg codec libraries.

**Comment by AkazaDorian** [comment]
Just got reminded that maybe we could do a PWA version using https://www.pwabuilder.com/ , so it might be opened in desktop "relatively natively"?

**Comment by planecore** [comment]
> <img alt="screenshot 2019-01-24 at 01 23 48" width="1456" src="https://user-images.githubusercontent.com/9306474/51668187-7c171400-1f76-11e9-9eb0-70e1beb13628.png">
> 
> (Also, a cute little progress picture)

Are you still developing the Electron app?

**Comment by picknassaro** [comment]
If you want to use Edge for Mac or Chromium Edge for Windows: you can do a sort of “Install a Website as an App” thing: https://pureinfotech.com/install-website-app-edge-chromium/

Chrome does this too: https://support.google.com/chrome_webstore/answer/3060053?hl=en

**Comment by nobodywasishere** [comment]
PWA doesn't support Linux I don't think.

Don't know if this is relevant:
https://stackoverflow.com/questions/23293782/mvc-web-api-405-method-not-allowed#23311611

**Comment by nobodywasishere** [comment]
@LP0101 Could you upload what you have? I want to take a look at it when you get the chance.

Along the same track: https://stackoverflow.com/questions/53906147/apples-javascript-musickit-api-authorize-in-electron-app

**Comment by LP0101** [comment]
@nobodywasishere There isn't much here really, you can see my package.json and html file here: https://github.com/LP0101/musish-nwjs

You can download nwjs from [here](https://nwjs.io/), and you can build ffmpeg from [here](https://github.com/iteufel/nwjs-ffmpeg-prebuilt). I've already included the latest ffmpeg library file for Linux x64 in the repo.

For reference, the error I get when trying to play something is:

```
[6143:6275:0715/101522.690636:ERROR:render_media_log.cc(27)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: open context failed"}
[6143:6143:0715/101522.690792:ERROR:render_media_log.cc(27)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_COULD_NOT_OPEN
```

Let me know if you find anything.

**Comment by JarekToro** [comment]
https://github.com/JarekToro/Apple-Music-Mpris This is what I use daily. Its an electron App that wraps the Musish webpage. It does however integrate with the events that MusicKit provides and connects with the mpris dbus on linux. And can be controlled from like other media applications from other mpris enabled controllers. Login also works and ive never had a problem with it even with 2fa enabled.

**Comment by andersfischernielsen** [comment]
Closing, since this seems to not be planned

**Comment by nobodywasishere** [comment]
For those looking for an alternative, [Cider](https://cider.sh/)  worked really well for me.
