### ISSUE TITLE
BUG:Drag n Drop not working

### ISSUE THREAD

**Issue by 2commakid** [Musish/Musish#239]
**Describe the bug**
Drag m4a file to library or playlist not being added

**To Reproduce**
1. drag file from finder on macos 
2. drop onto library or playlist

**Expected behavior**
file gets added (uploaded) to library (itunes match)

**Screenshots**

**Desktop (please complete the following information):**
 - macOS 10.14.2
 - Safari 12.0.2

**Comment by BrychanOdlum** [comment]
Musish does not support uploading songs from your computer to your iTunes Match / iCloud library. This is an Apple Music limitation. Songs should be added through Apple Music itself.

To add a song to your library use the search bar at the top right to enter a search phrase, hit enter to open the full search page, and from here you can either right click on an item and add it to your library or drag it into your library or a specific playlist on the sidebar.
