### ISSUE TITLE
BUG: For You page loading placeholder stays forever

### ISSUE THREAD

**Issue by dedeswim** [Musish/Musish#242]
**Describe the bug**
After I open the "For You" page and the content loads, on top of the page, there is still a loading placeholder that stays there forever.

**To Reproduce**
1. Go to 'For You'
2. Wait for content to load

**Expected behavior**
Once the content is loaded, the placeholder should disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/4366950/51597919-b6dc6600-1efc-11e9-97d1-9d70be183db7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browsers: Chrome 71, Firefox Developer Edition 65.0b12

I took a look around, I hope this is not duplicate.

**Comment by codymikol** [comment]
Do you have an apple music subscription? Could be related: #228

**Comment by dedeswim** [comment]
Yep, I do 😄

**Comment by BrychanOdlum** [comment]
Can confirm, this happens when no data is returned. Will push a fix ASAP.
