### ISSUE TITLE
Horizontal scrollbar is too thin.

### ISSUE THREAD

**Issue by irvingtelder** [Musish/Musish#254]
Horizontal scrollbar is too thin. Scrolling troublesome without trackpad or Magic Mouse.

**Comment by jamesjarvis** [comment]
Similar to #235 - scrollbars need to be looked at a little bit for various browsers

**Comment by FilipGrebowski** [comment]
This issue is being worked on. :)

**Comment by napieralla** [comment]
Addressed in https://github.com/Musish/Musish/pull/492 which made the horizontal scrollbar slightly thicker. I think that's as thick as we can make it without making it look ugly.

Consider closing this issue.

PS. The mouse-wheel scrolls horizontally when holding Shift, try this if you still think that grabbing the scrollbar is difficult.
