### ISSUE TITLE
Currently getting a 403 error on musi.sh

### ISSUE THREAD

**Issue by mrjamesjarvis** [Musish/Musish#26]
If you've been logged in for too long the bearer token appears to expire.
At the point of getting a 403 we should just return the user to the login screen.

**Comment by BrychanOdlum** [comment]
Further to this, it'd be nice to have alert notifications for network requests in the UI itself, but for now this is not a priority.

**Comment by FilipGrebowski** [comment]
This has been resolved and solution merged to master.

**Comment by BrychanOdlum** [comment]
Tested with Raphael last night and we had issues with expired tokens, need to rework this slightly.
