### ISSUE TITLE
BUG: Is "Add to Playlist" working? 

### ISSUE THREAD

**Issue by DiegoMarcondesD** [Musish/Musish#267]
**Describe the bug**
I can see the option "add to library" but it's not working for me. I get the message "Added to your playlist. It'll show up in a few seconds. Hold Tight!" but after minutes the song doesn't appear on the playlist.
I've tested the option to drag n drop too, it's not working for me.

**Desktop 
 - Browser chrome 71.0.3578.98 64 bits

**Comment by smitty-rh** [comment]
Agreed, went through adding a bunch of songs, only to find they were not really going anywhere.

**Comment by BrychanOdlum** [comment]
I'm unable to reproduce this, can you confirm which page / modal you're trying to add a track from?

Which song? It can take a few seconds to add the song to your library.

After refreshing the whole Musish app in your browser window does the song still not appear?

**Comment by smitty-rh** [comment]
I would search for a band in the top right corner, which would load the popular songs from them.  And from there would hit the button to choose to add to playlist from the pop up window.  I did this yesterday and the list has not added one of the 15+ songs I had added.  I will try again and see if it is still happening.

**Comment by smitty-rh** [comment]
So far the issue seems to still exist for me.  I am using Chrome on Fedora 29.  I will test with firefox and see if that is any different.

**Comment by smitty-rh** [comment]
Same issue, here are the steps if you would like to attempt to recreate the issue.

1. Top right, search for scars and hit enter
2.  From the songs list, I hit the three dots on the third one down from I Prevail (https://musi.sh/search/catalog/scars)
3.  Choose add to playlist
4.  Box pops up, I chose my Rock playlist
It then has a green message in the top corner stating that it may take a couple minutes, but the list never gets the song added.  As stated above, this is not one song specific as I had added 15+ songs only to find out they never were actually added.

Hope that might help.

**Comment by smitty-rh** [comment]
As a note, dragging the file to the playlist also doesn't do anything for me.

**Comment by BrychanOdlum** [comment]
Sorry, I am definitely wrong on this one! I read the start of the description "I can see the option "add to library" but it's not working for me." and began testing add to library, not add to playlist.

I've reproduced this with add to playlists and will look into it later today. Thanks for the report!
