### ISSUE TITLE
SECURITY? developer JWT is exposed in chrome devtools

### ISSUE THREAD

**Issue by Nukki** [Musish/Musish#268]
**Describe the bug**
Potential for abuse: the JWT token is exposed on the front end.

**To Reproduce**
1. Go to Chrome dev tools
2. In the console type `MusicKit.getInstance().api` and press Enter
3. Open the API object
3. Scroll down to `_developerToken`
4. See a valid token that can be used by anyone to authenticate with Apple Music API (with no dev account)

**Expected behavior**
Not being able to see a valid JWT auth token for Apple Music API

**Screenshots**
<img width="652" alt="screen shot 2019-01-29 at 9 37 31 am" src="https://user-images.githubusercontent.com/15151051/51916922-5772d000-23ac-11e9-9dc6-f0d8018f5334.png">

**Desktop :**
 - OS: Mac Os X Mojave
 - Browser Chrome
 - Version 71.0.3578.98

**Comment by BrychanOdlum** [comment]
I'm not sure if this is avoidable due to the nature of how JWTs work
