### ISSUE TITLE
FEATURE ability to set sound quality

### ISSUE THREAD

**Issue by nubstik** [Musish/Musish#275]
I don't see the ability to set the sound quality. What is the playback quality set to by default? I'd like to be able to see this information and change the setting.

**Comment by brianclinkenbeard** [comment]
[Zachary Seguin Music](https://music.zacharyseguin.ca/settings) ([source](https://github.com/zachomedia/apple-music-webplayer)) has the ability to set the bitrate to either 64 or 256 kbps. I believe MusicKit JS uses 64 kbps by default.
