### ISSUE TITLE
BUG: Request blocked by CORS policy

### ISSUE THREAD

**Issue by maddinat0r** [Musish/Musish#293]
Some songs just do not play when clicked on. Inspecting the console tab reveals this:
```
Access to fetch at 'https://aod-ssl.itunes.apple.com/itunes-assets/Music128/v4/79/14/48/79144841-7cd7-3c51-86a6-c3212d0bc536/mzaf_A1441084387.rmhq.aac.wa.mp4' from origin 'https://musi.sh' has been blocked by CORS policy: Request header field range is not allowed by Access-Control-Allow-Headers in preflight response.
```
![image](https://user-images.githubusercontent.com/1799378/52520908-94be4400-2c6f-11e9-9e79-b2308dce47be.png)

Here's the relevant code pretty-printed:
![image](https://user-images.githubusercontent.com/1799378/52520939-e36bde00-2c6f-11e9-905f-fa730ab76e4c.png)

Happens on Chrome 71.0.3578.98 (Windows 10 x64).

**Comment by raphaelvigee** [comment]
This problem seems to be on Apple Side

**Comment by michelmelo** [comment]
from origin 'https://musi.sh' has been blocked by CORS policy: Request header field range is not allowed by Access-Control-Allow-Headers in preflight response.
