### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by RobotDavid** [Musish/Musish#303]
Hi there!

This isn't a bug or feature request and I'm not too sure how GitHub works but I just wanted to say thank you to the developers for making this! 

Using iTunes on Mac and PC is a sluggish chore and this web interface is sleek, quick, and responsive.
A job well done!

**Comment by jamesjarvis** [comment]
Thank you very much! It's always nice to hear that people are enjoying using Musish @BrychanOdlum @raphaelvigee @FilipGrebowski
