### ISSUE TITLE
BUG: bassy songs

### ISSUE THREAD

**Issue by Leogir** [Musish/Musish#320]
**Describe the bug**
I tried playing music today from my Opera browser when I experienced that the bass in songs makes it sound like my headphones are broken. I tried Musish from my installed iTunes client, Chrome and Vivaldi browser and the bass there sounds completely ok. I compared with the same songs.

It's just Musish from the Opera browser that sounds like the bass equalizer is through the roof. I also tried playing the same songs from Youtube with the Opera browser just to compare if something was wrong with my settings on Opera but from other sources except Musish the sound is completely fine in Opera.

**To Reproduce**
1. Play any song with high bass like EDM, Techno etc.
2. Hear the crackling bass.

**Expected behavior**
Normal and clear bass

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera 
 - Version 58.0.3135.79 stable/latest as of today

**Additional context**
Regular AUX headphones connected directly to the motherboard (desktop PC).

**Comment by jamesjarvis** [comment]
I cannot reproduce, does this happen every time you play a song?

**Comment by raphaelvigee** [comment]
This is probably because Opera doesnt support the DRM Apple uses, and allows you to stream low quality only.
Chrom ftw :)

**Comment by Leogir** [comment]
I found out that it was the Opera Turbo setting that was creating this issue for me. When I disabled Turbo and restarted my browser the sound was good as it should be. I then tried activating it again and the sound was good then as well.

> Information from Opera about this feature:
> 
> The pages you visit go through one of our servers. The server identifies pieces of the page that can be compressed. It shaves off image pixels and corrects video buffering. Then, it sends back these smaller-sized pieces to your device.
> 
> https://www.opera.com/turbo
