### ISSUE TITLE
Web Worker instead of AWS Lambda Functions

### ISSUE THREAD

**Issue by kbumsik** [Musish/Musish#337]
Hi,
Thank you for this awesome app!
I'm currently learning web apps development and I'm looking through Musish code for learning.

After I skimmed backend code a little bit I thought it can run in a browser too. If the performance matters we could run it in a web worker. By this way we can make it more local...ish app that doesn't depend on additional services other than Apple Music, and we could cut operation cost.

Is there specific reason to run this on a serverless service? If you guys think it is okay to run this in a web worker, I would like to contribute.

Regards

**Comment by raphaelvigee** [comment]
Running it as a Lambda (among other things) allows us to benefit from Cloudflare's caching and leverage Amazon's computation power. This is not the right use case for web workers.
