### ISSUE TITLE
FEATURE

### ISSUE THREAD

**Issue by destroyzer** [Musish/Musish#340]
Are you guys planning to translate your app into Portuguese Brazilian?

I am a volunteer translator and have already translated applications like TweetDeck, Twitter, some games, and more recently I translated an application for League of Legends called Blitz, and I finished a month ago the application Black Menu for Google Chrome.

I'd love help you to translate your app or the games.

Thank you.

**Comment by raphaelvigee** [comment]
Feel free to checkout the repo and add the Portuguese  translation !

**Comment by destroyzer** [comment]
> Feel free to checkout the repo and add the Portuguese translation !

I can't upload please send the text I don't know how to use this service.

The link to the file (text file json):

https://drive.google.com/file/d/1MW7T6eB-l4HOZGfqjjHS1EwKGVvpQfuE/view?usp=sharing

Please use this as BrazilianPortuguese.json

And the display language is Português (Brasil).

Thank you @raphaelvigee
