### ISSUE TITLE
BUG: Login 502

### ISSUE THREAD

**Issue by yeucodonvn** [Musish/Musish#347]
**Describe the bug**
i cannot login to apple account
if I using VPN login succeed but when i reload browser Musish back to homepage and log out my account

**To Reproduce**
1. Click Login
2. A popup window appears
3. See error
![image](https://user-images.githubusercontent.com/18210504/55473153-1ca14880-5638-11e9-86bb-226b680d5209.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Chrome
 - Version: 73.9

**Comment by raphaelvigee** [comment]
This is a server-side issue on Apple's side

**Comment by yeucodonvn** [comment]
and i have other error. 
if I using VPN login succeed but when i reload browser Musish back to the homepage and log out my account
this is GIF error
![erro](https://user-images.githubusercontent.com/18210504/55540176-9b57bd80-56ec-11e9-8bc7-7e9fe3d1057e.gif)
