### ISSUE TITLE
BUG: Last.fm scrobbles

### ISSUE THREAD

**Issue by pusherbox** [Musish/Musish#348]
**Describe the bug**
Lst.fm scrobbles also skipped songs (or listened for a couple of seconds)

**Expected behavior**
It would be nice that only songs listened for at least the half of their lenght would be scrobbled

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 73.0.3683.86

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brianclinkenbeard** [comment]
Here's some documentation about this: https://www.last.fm/api/scrobbling#when-is-a-scrobble-a-scrobble

**Comment by paindefender** [comment]
https://github.com/Musish/Musish/blob/5a537a89b2eeaa6f2f9bb3fd2e268aa68197871d/src/app/components/LastfmProvider.jsx#L150-L154
there should be an additional listen time check here

**Comment by napieralla** [comment]
Resolved with https://github.com/Musish/Musish/pull/495.
A scrobble now happens as per Last.fm's [recommendations](https://www.last.fm/api/scrobbling#when-is-a-scrobble-a-scrobble).

This issue can be closed.
