### ISSUE TITLE
FEATURE - translation portuguese brazilian language

### ISSUE THREAD

**Issue by destroyzer** [Musish/Musish#349]
Sorry I don't know how to use this service (github).

I tried to upload the file but I got an error "please push something" and I don't know how to do that.

I translated the file json with the portuguese strings. Please can someone upload into the app?

https://drive.google.com/file/d/1MW7T6eB-l4HOZGfqjjHS1EwKGVvpQfuE/view?usp=sharing

Thank you!

**Comment by michelmelo** [comment]
@destroyzer  ja adicionei, vamos ver se é aprovado.
