### ISSUE TITLE
FEATURE: Prevent music pausing on tab A when tab B opens

### ISSUE THREAD

**Issue by dutzi** [Musish/Musish#359]
The problem: After opening one tab of musi.sh and playing some music, I'll usually open a second one and search for music in (Chrome allows searching by typing "musi{tab}" in the url bar, which is very convenient), once the second tab opens up the music in the first one pauses (even before I play any music in the second tab).

The solution, if possible, is to prevent the first tab from pausing until music gets played in the second one.

**Comment by jamesjarvis** [comment]
Unfortunately, this is a musickit limitation. As it instantiates a new session each time it is loaded.

You are still able to search for music whilst playing a song in Musish, and that’s the recommended way to use it.
