### ISSUE TITLE
BUG: music not playing

### ISSUE THREAD

**Issue by BriNyeTheScienceGuy** [Musish/Musish#364]
**Describe the bug**
Audio doesn't play on chromium browser. Tested on Chrome and Firefox, works fine on those.

**To Reproduce**
Go to musi.sh
login to Apple Music
Click Play on any song

**Desktop (please complete the following information):**
 - OS: Pop! OS
 - Browser: Chromium

**Comment by raphaelvigee** [comment]
Probably a DRM issue
