### ISSUE TITLE
BUG: Playing a new song from an album causes the song's duration to flash to NaN for a second

### ISSUE THREAD

**Issue by martineso** [Musish/Musish#365]
**Describe the bug**
When you select a song from an album that hasn't been played the song's duration in the player will flash to NaN before the actual time is shown.

**To Reproduce**
1. Open an album and play a certain song
2. Check the duration in the player 

**Expected behavior**
Should most likely show 00:00 before the actual time is shown

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version 66.0.3 (64-bit)

**Possible solution**
We can tweak the _getTime_ function in **Utils.js** to check if the passed _ms_ value is undefined or NaN and then set the ms to 0 if that is the case
e.g.

```
export function getTime(ms) {
  if (!ms || isNaN(ms)) ms = 0;
  const s = 1000 * Math.round(ms / 1000);
  const d = new Date(s);

  return `${d.getUTCMinutes()}:${String(`0${d.getUTCSeconds()}`).slice(-2)}`;
}
```

**Comment by jamesjarvis** [comment]
Looks like a good idea! I'm happy you've provided an example, could you submit a PR to incorporate your changes?

**Comment by martineso** [comment]
Alright. I am away from a pc for the weekend, will do first thing next week.
