### ISSUE TITLE
Desktop Build using Electron 

### ISSUE THREAD

**Issue by MichaelFay** [Musish/Musish#367]
**Is your feature request related to a problem? Please describe.**
It would be very nice if this could be wrapped in something like electron js so it could be used as a standalone desktop application. 

**Describe the solution you'd like**
Use electron js to build a desktop variant of this application.

**Comment by BrychanOdlum** [comment]
Duplicate of #238 

(TLDR: having issues authenticating with Apple, currently not possible (at least not by any method I've found)
