### ISSUE TITLE
BUG: Gapless album playback has silence between tracks

### ISSUE THREAD

**Issue by peppy** [Musish/Musish#374]
**Describe the bug**
When playing a gapless album, there is a noticeable delay between tracks as the next track presumably loads.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a gapless album playing (Example: Spencer Brown - Illusion of Perfection)
2. Wait for a track to play and end

**Expected behaviour**
Playback should continue with no gap

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0.3729.108 (Official Build) (64-bit)

**Comment by jamesjarvis** [comment]
This is a music kit limitation, and as far as I am aware we are not able to solve.

**Comment by peppy** [comment]
Unfortunate, but thanks for the info.
