### ISSUE TITLE
BUG: Volume can't be ajusted

### ISSUE THREAD

**Issue by Hirevo** [Musish/Musish#387]
**Describe the bug**
Volume can't be ajusted any more.  
It stays at 100%.
The mute button also broke.

This appears to be a MusicKit JS update that made `MusicKit.Player.volume` a getter-only property.
This issue also appears in my own [MusicKit Player](https://github.com/Hirevo/musickit-player).

**To Reproduce**
1. Play any song
2. Attempt to change or mute the volume.

**Expected behavior**
Volume to be adjusted or muted.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Firefox Nightly 69.0a1 & Safari 12.1.2

**Comment by jamesjarvis** [comment]
well spotted! Yes, it seems that apple has changed the volume attribute to readonly (https://developer.apple.com/documentation/musickitjs/musickit/player/2992775-volume). However, I can't find any other methods they have for volume control, besides a mute method (which only mentions setting the volume to 0, whether this also controls unmute functionality idk) https://developer.apple.com/documentation/musickitjs/musickit/player/2992755-mute

**Comment by Hirevo** [comment]
I couldn't find any official alternative either.

But then I inspected the player object itself in the console, and it turns out that there is `player._currentPlayer._volume` that is a mutable property (still a number between 0 and 1) and has the effect of changing the volume just like `player.volume` before (it's most likely the value behind the getter).
It's a bit reaching into the internals.

Another option would be that, since MusicKit JS inserts an `<audio>` element into the page to play audio, we can get a reference to that element from the DOM and mutate its `volume` property directly.  
In fact, `player._currentPlayer._volume` (and, by extension, `player.volume`) is synchronized to that value.

That's the options that I've found for now.

(As for `player.mute()`, I didn't know either if it toggled on and off, so I tested it and it doesn't unmute. 😕)

**Comment by jamesjarvis** [comment]
Supposedly, this will be fixed with a future release of music kit. Since there is no elegant way to fix this right now, we are going to sit back and see if it just fixes itself over the coming weeks 😂 I'll close this issue if that does happen.

**Comment by BrychanOdlum** [comment]
Looks to be fixed.

**Comment by Andrewjeska** [comment]
Just for my knowledge, what is the API call to adjust the volume? I don't see it anywhere in the docs.
