### ISSUE TITLE
Why is there Google Analytics tracking (and why isn't it advertised or opt-in)?

### ISSUE THREAD

**Issue by baileyparker** [Musish/Musish#409]
This `<GoogleAnalyticsProvider>` component appears to be injected into every page: https://github.com/Musish/Musish/blob/efde154ea89243b5d8825801a217726586626d98/src/app/components/Providers/GoogleAnalyticsProvider.jsx

It appears that it sends a Google Analytics ping on every page navigation:

```js
this.props.history.listen(location => {
        window.ga('set', 'page', location.pathname + location.search);
        window.ga('send', 'pageview');
});
```

Why is this there? This doesn't appear to be opt-in. Are you certain that no personal information is ever found in the path or querystring?

According to your [splash screen](https://musi.sh/):

![Splash Screen](https://user-images.githubusercontent.com/7943649/58654447-eacdfa80-82e5-11e9-954c-00d0791061e8.png)

> Our service does not access, collect, or store any personal or account information.

This certainly doesn't seem to be the case (unless you don't consider listening habits, playlist names/identifiers, searches, etc. to be "personal information").

**Comment by BrychanOdlum** [comment]
The GA data is not user-identifiable, we can not see which user listened to what, which user searched for what, when a user accessed Musish, where the user is from or what device they were using. We are not able to trace which routes a user accessed or which users accessed a given route.

We never send GA a user identifier. All we can know is how many searches were made for 'Darude  Sandstorm' or how many times Darude's page was viewed, however we can not see which users these views were made by.

If you have any suggestions on how we can improve our GA practice then please feel free to drop a comment here or open a PR.

**Comment by BrychanOdlum** [comment]
Also, if you feel more comfortable self-hosting and removing the GA support then you are more than welcome.

**Comment by baileyparker** [comment]
I appreciate the quick reply and your attention to this! :smile:

I also really appreciate the transparency on the API usage and the restrictions of the access it grants. That's why I was initially surprised by the addition of GA.

> The GA data is not user-identifiable, we can not see which user listened to what, which user searched for what, when a user accessed Musish, where the user is from or what device they were using. We are not able to trace which routes a user accessed or which users accessed a given route.

When you say "a user" you refer to a specific user. And sure, perhaps you cannot directly determine these things for a specific user. But GA does (AFAIR), collect URLs, device UAs, times, IPs (anonymized to "state" or "city" level--whatever that means for the user's country of origin), etc. Is that incorrect? If I remembered correctly, you could in theory (by using a series of filters based on UA and rough location) deanonymize (or mostly deanonymize) that information.

I worry that someone adding a feature (with no malicious intent) might accidentally let some PII spill into querystring params. Are there checks in place to ensure this doesn't happen?

> We never send GA a user identifier. All we can know is how many searches were made for 'Darude Sandstorm' or how many times Darude's page was viewed, however we can not see which users these views were made by.

Indeed you don't. But GA does set cookies that allows Google to identify users across sites. So, while you may not directly have this information, if they were so inclined, Google could access it. You can certainly conceive a scenario where Google could use the routes visited that you provide to extract search terms and use this to profile users (for example, recording that someone listens to a particular type of religious music). Perhaps this is a little tinfoil hat-y, but it is not beyond the realm of possibilities.

> Also, if you feel more comfortable self-hosting and removing the GA support then you are more than welcome.

Certainly, but that's an awfully high bar to just opt out of some tracking. Savvy users also probably have NoScript installed and block GA in the first place. But that's not really the point. The point is the intention and optics. Which brings me to:

> *We really do our best to make sure we have no access to personal or user-identifiable information stored. We have no intention to log any user's data, habits, or preferences. We have no use for it.*

I respect this position. But this intention and the fact that you have "no use for it" directly contradicts  your inclusion of GA. If you have no use for it, why insert it in the first place? Or do you have a use for it? I could imagine surveying UAs to make decisions about what browser versions to support. But, for that you could just do some analysis on your HTTP logs (or if you don't have access to those, setup a little server that you ping that records UAs).

IANAL, but I'd imagine including this has some GDPR ramifications.

I think an easy solution here is to add a settings toggle for enabling GA. Ideally, it would be opt-in.

I'd be willing to do the leg work on a PR for this if this is something that you'd be willing to merge.
