### ISSUE TITLE
BUG: Blank White Screen on Edge

### ISSUE THREAD

**Issue by AshyAspen** [Musish/Musish#415]
**Describe the bug**
When the website "loads" it... doesn't load. The browser may say it's done loading, but there simply a white screen. 

**To Reproduce**
1. Open edge
2. Go to 'musi.ish'
3. See blank white screen

**Expected behavior**
I expected the standard redish page with the apple id login like what appears on chrome and on safari on my iPhone to appear.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/48628344/58918457-59e98b80-86f8-11e9-88b1-d3865554b450.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, Version 1803, OS Build 17134.799
 - Browser: Microsoft Edge 42.17134.1.0 
 - Version: Not sure, accessed online 6/4/2019 (m/d/yyyy)

**Additional context**
Possibly related to #307? Mine never "flashes" though.
Also works fine on chrome, but not edge for some reason. Not sure what the issue is. Any steps I should take?

**Comment by BrychanOdlum** [comment]
Is this still happening?
