### ISSUE TITLE
Donation information

### ISSUE THREAD

**Issue by ffleming** [Musish/Musish#425]
I work in a shop where all workstations are Linux.  I live in a home where all computers and phones are Apple, and most services are also Apple.  I am one of those people who doesn't just _use_ Apple Music, but prefers it to Spotify etc.

What I'm saying is, Musi.sh makes my life just a little bit better, and I want to support it in a way other than sending PRs.  I don't care if that means funding bounties or hitting up Patreon or what, but throwing a donation/Patreon/whatever link up would be awesome.

Thanks!

**Comment by jamesjarvis** [comment]
We are over the moon that Musish could improve your life by even a little bit! 😄
We've started setting up an open collective, where we can list our yearly expenses and allow anyone who feels welcome to contribute to the open source project to be able to send a little bit of money.

You can find our page here:
https://opencollective.com/musish

Thanks to you too!

**Comment by ffleming** [comment]
Awesome, thanks! :D
