### ISSUE TITLE
BUG: Cant goto browse page

### ISSUE THREAD

**Issue by Ringtved** [Musish/Musish#440]
Iam not sure if this is only for me but I got a clean install
1. Go to '/browse'
2. See error
![Udklip](https://user-images.githubusercontent.com/42972425/62926590-1d4fa580-bdb5-11e9-9081-47049f9c2069.JPG)

**Comment by benvblanco** [comment]
@Ringtved , I cleared my cache and re-authenticated with Apple to get it working again. However, without authentication the Browse page is throwing an error.

**Comment by Ringtved** [comment]
You are the man it is working for me too

**Comment by BrychanOdlum** [comment]
Super strange. Is this still happening when you open a private / incognito tab and go to Musish unauthenticated?
