### ISSUE TITLE
BUG: Right click -> Add to Playlist doesn't do anything

### ISSUE THREAD

**Issue by Aerozolic** [Musish/Musish#441]
Right clicking on a song and selecting Add to Playlist doesn't do anything

**To Reproduce**

1. Right click on a song
2. Add to Playlist
3. Nothing happens

**Expected behavior**
Not sure what's supposed to happen because I haven't used this feature before. I guess a list of available playlists should open.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 76

**Comment by Ritooon** [comment]
Have the same bug, some more information on the development tool : 

`Uncaught TypeError: r is not a function
    at onClick (TrackContextMenu.jsx:53)`

**Comment by raphaelvigee** [comment]
Should be fixed by #438

**Comment by raphaelvigee** [comment]
Reopening since it isnt fixed
