### ISSUE TITLE
BUG: Missing License

### ISSUE THREAD

**Issue by dannyeei** [Musish/Musish#481]
I was wanting to fork this project but realised there isn't a license. Would you be able to do that? I'd recommend MIT license.

Incredible app! I'm really impressed with what you've managed to accomplish!

**Comment by BrychanOdlum** [comment]
Musish is distributed under the AGPL v3 license, you can find this in the project's root directory in the `/LICENSE` file.

We opted against MIT as we want derivative work to be published open source (to avoid Musish being used commercially by a third party). If you're making a public fork, feel free to work on your own build!

**Comment by BrychanOdlum** [comment]
https://github.com/Musish/Musish/blob/master/LICENSE
