### ISSUE TITLE
FEATURE: Dark theme

### ISSUE THREAD

**Issue by ironbunny3** [Musish/Musish#482]
I would love to see a dark mode on Musish! Other than that it is a great browser replacement for apple music.

**Comment by CrunchyPebble** [comment]
@ironbunny3 [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) this extension for dark mode works for me on musish, and actually on a lot more websites, even Github right now. It works pretty well, I would recommend it if you like dark mode a lot.

**Comment by CrunchyPebble** [comment]
@ironbunny3 [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) this extension for dark mode works for me on musish, and actually on a lot more websites, even Github right now. It works pretty well, I would recommend it if you like dark mode a lot.

**Comment by raphaelvigee** [comment]
Duplicate #206
