### ISSUE TITLE
Update backend node to 14

### ISSUE THREAD

**Issue by raphaelvigee** [Musish/Musish#501]
https://github.com/Musish/Musish/blob/master/src/backend/serverless.yml#L8

@napieralla

**Comment by napieralla** [comment]
AWS only provides first-party support for Node.js v12 at this time.

Our options are to either:
1. Use the official Node.js v12 runtime, provided by AWS.
2. Build and deploy our custom Node.js v14 runtime.
3. Use someone else's prebuilt layer/runtime for Node.js v14.

I found build-files and even pre-built and published runtimes, for steps 2 and 3, [here](https://github.com/janaz/aws-lambda-node-runtime).
I think option # 1 would be best though, it's simple and enough for our purposes.
If AWS takes as long to release their first-party v14 runtime [as they did for their v12 runtime](https://aws.amazon.com/blogs/compute/category/programing-language/node-js/), then v14 will be released this November.
