### ISSUE TITLE
BUG: je ne comprends rien

### ISSUE THREAD

**Issue by virtuoseit** [Musish/Musish#507]
Bonjour à tous,

je suis navré mais je n'arrive vraiment pas à comprendre ce qu'il faut faire exactement pour faire tourner cette app.
y a til un procédure claire nette et précise de ce qui dois etre fait step by step ?
car là c'est trop compliqué on découvre qu'il faut un truc chez aws mais on c'est pas quoi faire puis un autre truc puis un autres... 

je trouve votre application super cool !

faire simple c'est possible ?
bien cordialement

**Comment by raphaelvigee** [comment]
You request is not really clear, if you mean self-hosting/dev setup, make sure to read the readme: https://github.com/Musish/Musish#self-hosting

**Comment by 0x750** [comment]
Bonjour @virtuoseit,

Que cherchez-vous à faire ? Utiliser l'application ou bien l'héberger vous-même ?

Bien cordialement,
Benoit

**Comment by virtuoseit** [comment]
Bonjour 0x750(Benoit)
les deux avec en cible l'héberger nous même.
bien cordialement,
Philippe
