### ISSUE TITLE
URGENT: Apple developer token has expired!

### ISSUE THREAD

**Issue by napieralla** [Musish/Musish#509]
`musi.sh` is down for all users because of an expired Apple developer token. Can someone with **CircleCI** priviliges please rebuild the deployment with new environment variables set ASAP? I have a developer token I can give you if you need one, leave me a message with your email in this thread and I will send it to you.

@Musish @raphaelvigee

**Comment by raphaelvigee** [comment]
It's fixed now! Sorry for the delay^^
